---
tunnels:
  # A tunnel can belong to a single tenant, or be multi-tenanted via a VNI field.
  foobar:
    # tep: 192.168.0.1:*,192.168.0.2:4789
    tenant: 0
    method: vxlan-dummy-l2
    src: 192.168.0.1
    dst: 192.168.0.2
    dport: 4789

  foobar2:
    tenant: 1
    method: vxlan-dummy-l2
    src: 192.168.0.1
    dst: 192.168.0.2
    dport: 4790

interfaces:
  tap0:
    tenant: 1000

  tap10:
    tenant: 1000

  tap1:
    tunnel-headend: true

nats:
  # A pool is a NAT instance.
  # Multiple tenants can share a NAT instance (and pool)
  # A NAT does not have a binding to a tenant?
  '1':
    pool-address: [123.123.123.123, 1.1.1.1]

tenants:
  0:
    context: 0
    forward-services: [vcdp-l4-lifecycle, vcdp-nat-output]
    reverse-services: [vcdp-l4-lifecycle, vcdp-tunnel-output]
    nat-instance: '1'

  1:
    context: 0
    forward-services: [vcdp-l4-lifecycle, vcdp-nat-output]
    reverse-services: [vcdp-l4-lifecycle, vcdp-tunnel-output]
    nat-instance: '1'
  2:
    context: 0
    forward-services: [vcdp-l4-lifecycle, vcdp-nat-output]
    reverse-services: [vcdp-l4-lifecycle, vcdp-tunnel-output]
    nat-instance: '2'

  1000:  # Outside tenant
    context: 0
    flags: no-create
    forward-services: [vcdp-bypass]

