name: Makefile CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Build NATaaS plugin
      run: make VPP_DIR=/usr/local/src/vpp build
      
    - name: Run check
      run: make check

    - name: Run feature tests
      run: make VPP_DIR=/usr/local/src/vpp test-debug
